второе домашнее задание
htmlacademy-htmlcss/1952749-device-33 pull request #2
Opened 2022-01-23 18:02 UTC by mevorik

2022-01-23 18:17 UTC, mevorik commented
второе дз

2022-01-23 18:54 UTC, vladpovelitsa requested changes
1. отформатируй код. Установи плагин https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode он делает это автоматически

2. лого должен быть ссылкой https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode

3. это не навигация, а форма поиска, её нужно сделать при помощи соответствующих тегов https://prnt.sc/26i5l0j

4. https://prnt.sc/26i5mdd это отдельный блок, он должен быть вне навигации.

5. тут явно что-то не так, закрывающий li и продолжение списка из неоткуда https://prnt.sc/26i5mn5

6. https://prnt.sc/26i5n0m список не нужен

7. подробнее - ссылка "800 м" и "50 м" должны быть в отдельном блоке со своим классом, чтобы ты их мог стилизовать потом https://prnt.sc/26i5net + нужны закрывающие теги </p> тег ul не нужен
 
 8. В тег main помещается все содержимое страницы, кроме футер, хедера и всплывающих окон 
 
 9. не закрыл тег ul https://prnt.sc/26i5net
 
это пока только первый экран. Пересмотри еще раз лайв и разберись с форматированием, многие ошибки из-за этого по аналогии с этими правками проверь остальной сайт, там тоже самое повторяется

2022-02-12 13:42 UTC, mevorik commented
второе домашнее задание, две страницы

2022-02-12 19:54 UTC, vladpovelitsa requested changes
Ты молодец! есть пара мелких замечаний и нужно немного поработать над фораматирование кода, но в целом видон, что ты очень хорошо поработал! Так держать.

2022-02-12 19:54 UTC, vladpovelitsa commented on cotalog.html
> +                  <input class="control-input" type="radio" name="No" value="care-products" checked>
если радиокнопки относятся к одной группе, то и name у них должен быть один, иначе они не будут связаны. т.е. тебе нужно задать обеим `<input name="bluethooth">` и соответствующие значения в value=""  (yes или no)

2022-02-12 19:54 UTC, vladpovelitsa commented on cotalog.html
> +            </a>
лишний закрывающий тег

2022-02-12 19:54 UTC, vladpovelitsa commented on cotalog.html
> +    <main class="catalog-products">
на странице может быть только тег `<main>` замени на `<section>`

2022-02-12 19:54 UTC, vladpovelitsa commented on index.html
> +</h3>
тег `<h3>` и другие h* необходимы для создания заголовка, в них не должны содержаться картинки `<p>` и т.д.

2022-05-19 20:27 UTC, closed without merging